{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rnusbcamera.ausbc",
    "module": "libuvc",
    "version": "3.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libuvc-3.4.5.aar",
          "url": "libuvc-3.4.5.aar",
          "size": 628573,
          "sha512": "96b92243fe0d57727c76efae7b9eceb4e9d5e2985f6d61022b427e407055deca0128f60abb4cb148e35b0bb2ad3f691a2cd6aa484105dc3ac06f434df70619e2",
          "sha256": "7705bf9b79eb13e483b65585a7a7464fb323dbd8e1d25edec6e2efe279b6c3e9",
          "sha1": "c69110859740a32d778faee967952d8d3d9e3a1d",
          "md5": "7d82a3b229f5f6ecc9e1dd39c58fee6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.elvishew",
          "module": "xlog",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "libuvc-3.4.5.aar",
          "url": "libuvc-3.4.5.aar",
          "size": 628573,
          "sha512": "96b92243fe0d57727c76efae7b9eceb4e9d5e2985f6d61022b427e407055deca0128f60abb4cb148e35b0bb2ad3f691a2cd6aa484105dc3ac06f434df70619e2",
          "sha256": "7705bf9b79eb13e483b65585a7a7464fb323dbd8e1d25edec6e2efe279b6c3e9",
          "sha1": "c69110859740a32d778faee967952d8d3d9e3a1d",
          "md5": "7d82a3b229f5f6ecc9e1dd39c58fee6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libuvc-3.4.5-sources.jar",
          "url": "libuvc-3.4.5-sources.jar",
          "size": 52937,
          "sha512": "243a4c76d8fee76b81cd4fd54866b115991cbd7dce8f996fa706c319807bbd5dd991983a82ab01864660e4093d84f61d28845e76d391886e6c79bba130233fe7",
          "sha256": "8e86de9c88baaa3f0d90a1ea1c3fbc8ee61e3fe74f2f089b363ec87ddde4dd70",
          "sha1": "8a454bba2484ffe70def3788a8057babb4708106",
          "md5": "92bbb3a6f33dc864a8bbe90ae3d76c3a"
        }
      ]
    }
  ]
}
