{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.ernestp",
    "module": "libnative",
    "version": "3.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "libnative-3.4.5.aar",
          "url": "libnative-3.4.5.aar",
          "size": 483685,
          "sha512": "9275755d4f1afa869aede66bfd30e2f123b1a4eb2e57088d7c753a98524c3d43e71c00f18fa275e404a301afba203256330eca7430cd795f6dd351562e2aa307",
          "sha256": "3581c7f8fa2d9b169331047d57019790cb9209a91c3b01a1368d017ab9bf86ce",
          "sha1": "504640753e8c85ea49bc901c43688e2850c99965",
          "md5": "90b62ea9b69108e8d46320d0468fd019"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "libnative-3.4.5.aar",
          "url": "libnative-3.4.5.aar",
          "size": 483685,
          "sha512": "9275755d4f1afa869aede66bfd30e2f123b1a4eb2e57088d7c753a98524c3d43e71c00f18fa275e404a301afba203256330eca7430cd795f6dd351562e2aa307",
          "sha256": "3581c7f8fa2d9b169331047d57019790cb9209a91c3b01a1368d017ab9bf86ce",
          "sha1": "504640753e8c85ea49bc901c43688e2850c99965",
          "md5": "90b62ea9b69108e8d46320d0468fd019"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libnative-3.4.5-sources.jar",
          "url": "libnative-3.4.5-sources.jar",
          "size": 1969,
          "sha512": "2f6994fab72dcb7fb598a9da563ce9132fbb2674523b80289e42aa6f65ff68774d5951022a41d023bdf9027fdebe3c125b4682d2c4aa403d4e3cd647f8708bf1",
          "sha256": "180b4de13ef67a4060ba41226315f5a71c2714757e70efbc57308f62c3610aec",
          "sha1": "dca4423e120403d655f1076cfec5e517abe38699",
          "md5": "4726e2e40eca1b843f534fad02046af2"
        }
      ]
    }
  ]
}
